jdk:
  - oraclejdk8
language: android
android:
        components:
                - platform-tools
                - build-tools-28.0.0-rc1
                - android-27
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
